# Generated by Django 3.2 on 2022-04-02 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('index', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=300, verbose_name='username')),
                ('id', models.CharField(max_length=300, verbose_name='username')),
            ],
            options={
                'verbose_name': 'listener',
                'verbose_name_plural': 'listener',
            },
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=254)),
                ('guests', models.ManyToManyField(to='api.Listener')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='channel name')),
                ('rules', models.TextField(null=True, verbose_name='rules')),
                ('playlist_id', models.CharField(max_length=254, verbose_name='playlist id')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to='api.listener')),
                ('guests', models.ManyToManyField(to='api.Listener')),
                ('sync', models.ManyToManyField(to='api.Sync')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'room',
            },
        ),
        migrations.AddIndex(
            model_name='listener',
            index=models.Index(fields=['display_name'], name='lister_display_name_idx'),
        ),
    ]
