# Generated by Django 3.0.5 on 2022-03-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listener',
            options={'verbose_name': 'listener', 'verbose_name_plural': 'listener'},
        ),
        migrations.AlterField(
            model_name='listener',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
