# Generated by Django 3.2 on 2022-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='display_name',
            field=models.CharField(max_length=300, verbose_name='display_name'),
        ),
        migrations.AlterField(
            model_name='listener',
            name='id',
            field=models.CharField(max_length=300, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='room',
            name='sync',
            field=models.ManyToManyField(null=True, to='api.Sync'),
        ),
    ]
